artifact_location: /workspaces/mlops-zoomcap/02-experiment-tracking/02-experiment-tracking/mlflow.db/108006239296573863
creation_time: 1749115118672
experiment_id: '108006239296573863'
last_update_time: 1749115118672
lifecycle_stage: active
name: nyc-taxi-experiment
