artifact_location: /workspaces/mlops-zoomcap/02-experiment-tracking/02-experiment-tracking/mlflow.db/0
creation_time: 1749115118661
experiment_id: '0'
last_update_time: 1749115118661
lifecycle_stage: active
name: Default
